class ChaosSystemSettings {
	constructor () {
		this.maxDecals = 10
		this.staticDecals = false
		this.dynamicDecals = true
		this.unbatchedDecals = true
		this.dynamicLights = false
		this.dynamicShadows = false
		this.motionBlur = false
		this.depthOfField = false
		this.ambientOcclusion = false
		this.bloom = false
		this.distortion = false
		this.downsampledTranslucency = true
		this.speedTree = true
		this.volumetrics = true
		this.floatingPointRenderTargets = true
		this.oneFrameThreadLag = true
		this.vsync = false
		this.doubleBuffering = false
		this.tripleBuffering = false
		this.meshScreenPixelAreaThreshold = 256

		this.resolution = {x: 1920, y: 1080}
		this.screenPercentage = 100
		this.ssaa = 1.0
		this.fxaa = 0
		this.msaa = 1
		this.dx11 = true
		this.ragdolls = true

		this.filtering = "Aniso"

		this.charTextureRes = 64
		this.weaponTextureRes = 64
		this.mapTextureRes = 64

		this.skeletalMeshLODBias = 1
		this.particleLODBias = 10
		this.staticMeshLODBias = 1

		this.perFrameYield = true
	}
	get result () {
		let chaosSystemSettings = `[SystemSettings]
		MaxActiveDecals=${this.maxDecals}
		GameSettingsVersion=-1
		StaticDecals=${this.staticDecals}
		DynamicDecals=${this.dynamicDecals}
		UnbatchedDecals=${this.unbatchedDecals}
		DecalCullDistanceScale=0.400000
		DynamicLights=${this.dynamicLights}
		DynamicShadows=${this.dynamicShadows}
		LightEnvironmentShadows=False
		CompositeDynamicLights=False
		SHSecondaryLighting=False
		DirectionalLightmaps=True
		MotionBlur=${this.motionBlur}
		MotionBlurPause=True
		MotionBlurSkinning=1
		DepthOfField=${this.depthOfField}
		AmbientOcclusion=${this.ambientOcclusion}
		Bloom=${this.bloom}
		bAllowLightShafts=False
		Distortion=${this.distortion}
		FilteredDistortion=${this.distortion}
		DropParticleDistortion=${!this.distortion}
		bAllowDownsampledTranslucency=${this.downsampledTranslucency}
		SpeedTreeLeaves=${this.speedTree}
		SpeedTreeFronds=${this.speedTree}
		OnlyStreamInTextures=False
		LensFlares=False
		FogVolumes=${this.volumetrics}
		FloatingPointRenderTargets=${this.floatingPointRenderTargets}
		OneFrameThreadLag=${this.oneFrameThreadLag}
		UseVsync=${this.vsync}
		AllowDoubleRenderFrames=${this.doubleBuffering}
		ModulatedShadowStartFadeDistance=0.000000
		ModulatedShadowFullyFadeDistance=0.000000
		VsyncPresentInterval=1
		UseCinematicMipCalculations=True
		bUseTripleBuffering=${this.tripleBuffering}
		UpscaleScreenPercentage=True
		Fullscreen=True
		FullscreenWindowed=False
		MeshScreenPixelAreaThreshold=${this.meshScreenPixelAreaThreshold}.000000
		OctreeScreenPixelAreaThreshold=512.000000
		AllowOpenGL=False
		AllowRadialBlur=False
		UseDX11=${this.dx11}
		UseD3D11Beta=False
		bAllowTexturePack=True
		AllowSubsurfaceScattering=False
		AllowImageReflections=False
		AllowImageReflectionShadowing=True
		bAllowSeparateTranslucency=False
		bAllowPostprocessMLAA=False
		bAllowHighQualityMaterials=False
		MaxFilterBlurSampleCount=16
		SkeletalMeshLODBias=${this.skeletalMeshLODBias}
		ParticleLODBias=${this.particleLODBias}
		DetailMode=0
		MaxDrawDistanceScale=0.800000
		ShadowFilterQualityBias=-1
		MaxAnisotropy=0
		MaxMultisamples=${this.msaa}
		bAllowD3D9MSAA=False
		bAllowTemporalAA=False
		TemporalAA_MinDepth=500.000000
		TemporalAA_StartDepthVelocityScale=100.000000
		MinShadowResolution=32
		MinPreShadowResolution=8
		MaxShadowResolution=256
		MobileShadowTextureResolution=1120
		MaxWholeSceneDominantShadowResolution=256
		ShadowFadeResolution=128
		PreShadowFadeResolution=16
		ShadowFadeExponent=0.250000
		ResX=${this.resolution.x}
		ResY=${this.resolution.y}
		ScreenPercentage=${this.screenPercentage * this.ssaa}.000000
		SceneCaptureStreamingMultiplier=1.000000
		ShadowTexelsPerPixel=2.000000
		PreShadowResolutionFactor=0.500000
		bEnableBranchingPCFShadows=False
		bAllowHardwareShadowFiltering=False
		TessellationAdaptivePixelsPerTriangle=48.000000
		bEnableForegroundShadowsOnWorld=False
		bEnableForegroundSelfShadowing=False
		bAllowWholeSceneDominantShadows=False
		bUseConservativeShadowBounds=True
		ShadowFilterRadius=2.000000
		ShadowDepthBias=0.012000
		PerObjectShadowTransition=60.000000
		PerSceneShadowTransition=600.000000
		CSMSplitPenumbraScale=0.500000
		CSMSplitSoftTransitionDistanceScale=4.000000
		CSMSplitDepthBiasScale=0.500000
		CSMMinimumFOV=40.000000
		CSMFOVRoundFactor=4.000000
		UnbuiltWholeSceneDynamicShadowRadius=20000.000000
		UnbuiltNumWholeSceneDynamicShadowCascades=3
		WholeSceneShadowUnbuiltInteractionThreshold=50
		bAllowFracturedDamage=True
		NumFracturedPartsScale=1.000000
		FractureDirectSpawnChanceScale=1.000000
		FractureRadialSpawnChanceScale=1.000000
		FractureCullDistanceScale=1.000000
		bForceCPUAccessToGPUSkinVerts=false
		bDisableSkeletalInstanceWeights=false
		HighPrecisionGBuffers=False
		AllowSecondaryDisplays=False
		SecondaryDisplayMaximumWidth=1280
		SecondaryDisplayMaximumHeight=720
		AllowLogitechLedSdk=True
		AllowPerFrameSleep=${this.perFrameYield}
		AllowPerFrameYield=${this.perFrameYield}
		MobileFeatureLevel=0
		MobileFog=True
		MobileHeightFog=False
		MobileSpecular=True
		MobileBumpOffset=True
		MobileNormalMapping=True
		MobileEnvMapping=True
		MobileRimLighting=True
		MobileColorBlending=True
		MobileColorGrading=False
		MobileVertexMovement=True
		MobileOcclusionQueries=False
		MobileGlobalGammaCorrection=False
		MobileAllowGammaCorrectionWorldOverride=True
		MobileAllowDepthPrePass=False
		MobileGfxGammaCorrection=False
		MobileLODBias=-0.5
		MobileBoneCount=75
		MobileBoneWeightCount=2
		MobileUsePreprocessedShaders=True
		MobileFlashRedForUncachedShaders=False
		MobileWarmUpPreprocessedShaders=True
		MobileCachePreprocessedShaders=False
		MobileProfilePreprocessedShaders=False
		MobileUseCPreprocessorOnShaders=True
		MobileLoadCPreprocessedShaders=True
		MobileSharePixelShaders=True
		MobileShareVertexShaders=True
		MobileShareShaderPrograms=True
		MobileEnableMSAA=False
		MobileContentScaleFactor=1.0
		MobileVertexScratchBufferSize=150
		MobileIndexScratchBufferSize=10
		MobileLightShaftScale=2.0
		MobileLightShaftFirstPass=0.5
		MobileLightShaftSecondPass=1.0
		MobileModShadows=True
		MobileTiltShift=False
		MobileMaxMemory=300
		MobilePostProcessBlurAmount=32.0
		bMobileUsingHighResolutionTiming=True
		MobileTiltShiftPosition=0.5
		MobileTiltShiftFocusWidth=0.3
		MobileTiltShiftTransitionWidth=0.5
		MobileMaxShadowRange=500.0
		MobileBloomTint=(R=1.0,G=0.75,B=0.0,A=1.0)
		MobileClearDepthBetweenDPG=False
		MobileSceneDepthResolveForShadows=TRUE
		MobileLandscapeLodBias=0
		MobileUseShaderGroupForStartupObjects=FALSE
		MobileMinimizeFogShaders=FALSE
		MobileFXAAQuality=0
		ApexLODResourceBudget=1000000000000000000000.0
		ApexDestructionMaxChunkIslandCount=2500
		ApexDestructionMaxShapeCount=0
		ApexDestructionMaxChunkSeparationLOD=1.0
		ApexDestructionMaxActorCreatesPerFrame=-1
		ApexDestructionMaxFracturesProcessedPerFrame=-1
		ApexDestructionSortByBenefit=True
		ApexGRBEnable=false
		ApexGRBGPUMemSceneSize=128
		ApexGRBGPUMemTempDataSize=128
		ApexGRBMeshCellSize=7.5
		ApexGRBNonPenSolverPosIterCount=9;
		ApexGRBFrictionSolverPosIterCount=3;
		ApexGRBFrictionSolverVelIterCount=3;
		ApexGRBSkinWidth=0.025
		ApexGRBMaxLinearAcceleration=1000000.0
		bEnableParallelAPEXClothingFetch=True
		bApexClothingAsyncFetchResults=False
		ApexClothingAvgSimFrequencyWindow=60
		ApexClothingAllowAsyncCooking=True
		ApexClothingAllowApexWorkBetweenSubsteps=FALSE
		TargetFrameRate=60
		TEXTUREGROUP_World=(MinLODSize=${this.mapTextureRes},MaxLODSize=${this.mapTextureRes},MaxLODSizeTexturePack=${this.mapTextureRes},LODBias=3,LODBiasTexturePack=3,MinMagFilter=${this.filtering},MipFilter=Point,MipGenSettings=TMGS_SimpleAverage)
		TEXTUREGROUP_WorldNormalMap=(MinLODSize=${this.mapTextureRes},MaxLODSize=${this.mapTextureRes},MaxLODSizeTexturePack=${this.mapTextureRes},LODBias=3,LODBiasTexturePack=3,MinMagFilter=${this.filtering},MipFilter=Point,MipGenSettings=TMGS_SimpleAverage)
		TEXTUREGROUP_WorldSpecular=(MinLODSize=${this.mapTextureRes},MaxLODSize=${this.mapTextureRes},MaxLODSizeTexturePack=${this.mapTextureRes},LODBias=3,LODBiasTexturePack=3,MinMagFilter=${this.filtering},MipFilter=Point,MipGenSettings=TMGS_SimpleAverage)
		TEXTUREGROUP_Character=(MinLODSize=${this.charTextureRes},MaxLODSize=${this.charTextureRes},MaxLODSizeTexturePack=${this.charTextureRes},LODBias=2,LODBiasTexturePack=2,MinMagFilter=${this.filtering},MipFilter=Point,MipGenSettings=TMGS_SimpleAverage)
		TEXTUREGROUP_CharacterNormalMap=(MinLODSize=${this.charTextureRes},MaxLODSize=${this.charTextureRes},MaxLODSizeTexturePack=${this.charTextureRes},LODBias=2,LODBiasTexturePack=2,MinMagFilter=${this.filtering},MipFilter=Point,MipGenSettings=TMGS_SimpleAverage)
		TEXTUREGROUP_CharacterSpecular=(MinLODSize=${this.charTextureRes},MaxLODSize=${this.charTextureRes},MaxLODSizeTexturePack=${this.charTextureRes},LODBias=2,LODBiasTexturePack=2,MinMagFilter=${this.filtering},MipFilter=Point,MipGenSettings=TMGS_SimpleAverage)
		TEXTUREGROUP_Weapon=(MinLODSize=${this.weaponTextureRes},MaxLODSize=${this.weaponTextureRes},MaxLODSizeTexturePack=${this.weaponTextureRes},LODBias=2,LODBiasTexturePack=2,MinMagFilter=${this.filtering},MipFilter=Point,MipGenSettings=TMGS_SimpleAverage)
		TEXTUREGROUP_WeaponNormalMap=(MinLODSize=${this.weaponTextureRes},MaxLODSize=${this.weaponTextureRes},MaxLODSizeTexturePack=${this.weaponTextureRes},LODBias=2,LODBiasTexturePack=2,MinMagFilter=${this.filtering},MipFilter=Point,MipGenSettings=TMGS_SimpleAverage)
		TEXTUREGROUP_WeaponSpecular=(MinLODSize=${this.weaponTextureRes},MaxLODSize=${this.weaponTextureRes},MaxLODSizeTexturePack=${this.weaponTextureRes},LODBias=2,LODBiasTexturePack=2,MinMagFilter=${this.filtering},MipFilter=Point,MipGenSettings=TMGS_SimpleAverage)
		TEXTUREGROUP_Vehicle=(MinLODSize=${this.charTextureRes},MaxLODSize=${this.charTextureRes},MaxLODSizeTexturePack=${this.charTextureRes},LODBias=2,LODBiasTexturePack=2,MinMagFilter=${this.filtering},MipFilter=Point,MipGenSettings=TMGS_SimpleAverage)
		TEXTUREGROUP_VehicleNormalMap=(MinLODSize=${this.charTextureRes},MaxLODSize=${this.charTextureRes},MaxLODSizeTexturePack=${this.charTextureRes},LODBias=2,LODBiasTexturePack=2,MinMagFilter=${this.filtering},MipFilter=Point,MipGenSettings=TMGS_SimpleAverage)
		TEXTUREGROUP_VehicleSpecular=(MinLODSize=${this.charTextureRes},MaxLODSize=${this.charTextureRes},MaxLODSizeTexturePack=${this.charTextureRes},LODBias=2,LODBiasTexturePack=2,MinMagFilter=${this.filtering},MipFilter=Point,MipGenSettings=TMGS_SimpleAverage)
		TEXTUREGROUP_Cinematic=(MinLODSize=128,MaxLODSize=256,MaxLODSizeTexturePack=256,LODBias=2,LODBiasTexturePack=2,MinMagFilter=${this.filtering},MipFilter=Point,MipGenSettings=TMGS_SimpleAverage)
		TEXTUREGROUP_Effects=(MinLODSize=32,MaxLODSize=256,MaxLODSizeTexturePack=256,LODBias=2,LODBiasTexturePack=2,MinMagFilter=Linear,MipFilter=Point,MipGenSettings=TMGS_SimpleAverage)
		TEXTUREGROUP_EffectsNotFiltered=(MinLODSize=32,MaxLODSize=256,MaxLODSizeTexturePack=256,LODBias=2,LODBiasTexturePack=2,MinMagFilter=${this.filtering},MipFilter=Point,MipGenSettings=TMGS_SimpleAverage)
		TEXTUREGROUP_Skybox=(MinLODSize=64,MaxLODSize=256,MaxLODSizeTexturePack=256,LODBias=2,LODBiasTexturePack=2,MinMagFilter=${this.filtering},MipFilter=Point,MipGenSettings=TMGS_SimpleAverage)
		TEXTUREGROUP_UI=(MinLODSize=1,MaxLODSize=2048,MaxLODSizeTexturePack=2048,LODBias=0,LODBiasTexturePack=0,MinMagFilter=${this.filtering},MipFilter=Point,MipGenSettings=TMGS_SimpleAverage)
		TEXTUREGROUP_Lightmap=(MinLODSize=${this.lightingMapRes},MaxLODSize=${this.lightingMapRes},MaxLODSizeTexturePack=${this.lightingMapRes},LODBias=3,LODBiasTexturePack=3,MinMagFilter=${this.filtering},MipFilter=Point,MipGenSettings=TMGS_SimpleAverage)
		TEXTUREGROUP_Shadowmap=(MinLODSize=${this.lightingMapRes},MaxLODSize=${this.lightingMapRes},MaxLODSizeTexturePack=${this.lightingMapRes},LODBias=3,LODBiasTexturePack=3,MinMagFilter=${this.filtering},MipFilter=Point,NumStreamedMips=3,MipGenSettings=TMGS_SimpleAverage)
		TEXTUREGROUP_RenderTarget=(MinLODSize=1,MaxLODSize=2048,MaxLODSizeTexturePack=2048,LODBias=0,LODBiasTexturePack=0,MinMagFilter=${this.filtering},MipFilter=Point,MipGenSettings=TMGS_SimpleAverage)
		TEXTUREGROUP_MobileFlattened=(MinLODSize=1,MaxLODSize=4096,MaxLODSizeTexturePack=4096,LODBias=1,LODBiasTexturePack=1,MinMagFilter=${this.filtering},MipFilter=Point,MipGenSettings=TMGS_SimpleAverage)
		TEXTUREGROUP_ProcBuilding_Face=(MinLODSize=1,MaxLODSize=1024,MaxLODSizeTexturePack=1024,LODBias=1,LODBiasTexturePack=1,MinMagFilter=${this.filtering},MipFilter=Point,MipGenSettings=TMGS_SimpleAverage)
		TEXTUREGROUP_ProcBuilding_LightMap=(MinLODSize=1,MaxLODSize=256,MaxLODSizeTexturePack=256,LODBias=1,LODBiasTexturePack=1,MinMagFilter=${this.filtering},MipFilter=Point,MipGenSettings=TMGS_SimpleAverage)
		TEXTUREGROUP_Terrain_Heightmap=(MinLODSize=1,MaxLODSize=4096,MaxLODSizeTexturePack=4096,LODBias=0,LODBiasTexturePack=0,MinMagFilter=${this.filtering},MipFilter=Point,MipGenSettings=TMGS_SimpleAverage)
		TEXTUREGROUP_Terrain_Weightmap=(MinLODSize=1,MaxLODSize=4096,MaxLODSizeTexturePack=4096,LODBias=0,LODBiasTexturePack=0,MinMagFilter=${this.filtering},MipFilter=Point,MipGenSettings=TMGS_SimpleAverage)
		TEXTUREGROUP_ImageBasedReflection=(MinLODSize=256,MaxLODSize=4096,MaxLODSizeTexturePack=4096,LODBias=1,LODBiasTexturePack=1,MinMagFilter=${this.filtering},MipFilter=Linear,MipGenSettings=TMGS_Blur5)
		TEXTUREGROUP_Bokeh=(MinLODSize=1,MaxLODSize=256,MaxLODSizeTexturePack=256,LODBias=1,LODBiasTexturePack=1,MinMagFilter=${this.filtering},MipFilter=Linear,MipGenSettings=TMGS_SimpleAverage)
		TEXTUREGROUP_UIStreamable=(MinLODSize=1,MaxLODSize=2048,MaxLODSizeTexturePack=2048,LODBias=0,LODBiasTexturePack=0,MinMagFilter=${this.filtering},MipFilter=Point,NumStreamedMips=0,MipGenSettings=TMGS_SimpleAverage)
		bAllowRagdolling=${this.ragdolls}
		bAllowParticleSystemPerfBias=True
		bAllowPerfThrottling=false
		PerfScalingFramerateStart=30.000000
		PerfScalingFramerateRange=20.000000
		PerfScalingMaxReduction=0.600000
		PerfScalingBias=0.200000
		Borderless=False
		StaticMeshLODBias=${this.staticMeshLODBias}
		bAllowDropShadows=False
		SpeedTreeLODBias=2
		bUseLowQualMaterials=True
		bUseSpectatorTextureSettings=False
		TexturePoolSize=150
		AllowD3D11=False
		PreferD3D11=False
		FXAAQuality=${this.fxaa}
		AllowScreenDoorFade=False
		AllowScreenDoorLODFading=False
		bAllowFog=False
		MaterialQualityLevel=1
		SettingsVersion=9
		SpeedTreeWind=False
		TEXTUREGROUP_NPC=(MinLODSize=${this.charTextureRes},MaxLODSize=${this.charTextureRes},MaxLODSizeTexturePack=${this.charTextureRes},LODBias=1,LODBiasTexturePack=1,MinMagFilter=${this.filtering},MipFilter=Point,MipGenSettings=TMGS_SimpleAverage)
		TEXTUREGROUP_NPCNormalMap=(MinLODSize=${this.charTextureRes},MaxLODSize=${this.charTextureRes},MaxLODSizeTexturePack=${this.charTextureRes},LODBias=1,LODBiasTexturePack=1,MinMagFilter=${this.filtering},MipFilter=Point,MipGenSettings=TMGS_SimpleAverage)
		TEXTUREGROUP_NPCSpecular=(MinLODSize=${this.charTextureRes},MaxLODSize=${this.charTextureRes},MaxLODSizeTexturePack=${this.charTextureRes},LODBias=1,LODBiasTexturePack=1,MinMagFilter=${this.filtering},MipFilter=Point,MipGenSettings=TMGS_SimpleAverage)
		TEXTUREGROUP_WorldDetail=(MinLODSize=${this.mapTextureRes},MaxLODSize=${this.mapTextureRes},MaxLODSizeTexturePack=${this.mapTextureRes},LODBias=3,LODBiasTexturePack=3,MinMagFilter=${this.filtering},MipFilter=Point,MipGenSettings=TMGS_SimpleAverage)
		TEXTUREGROUP_TitleScreenPreview=(MinLODSize=1,MaxLODSize=2048,MaxLODSizeTexturePack=2048,LODBias=0,LODBiasTexturePack=0,MinMagFilter=${this.filtering},MipFilter=Point,MipGenSettings=TMGS_SimpleAverage)
		TEXTUREGROUP_ColorLookupTable=(MinLODSize=1,MaxLODSize=4096,MaxLODSizeTexturePack=1,LODBias=0,LODBiasTexturePack=0,MinMagFilter=${this.filtering},MipFilter=Point,MipGenSettings=TMGS_SimpleAverage)

		[SystemSettingsBucket1]
		BasedOn=SystemSettings
		MeshScreenPixelAreaThreshold=256.0
		OctreeScreenPixelAreaThreshold=512.0
		ResX=800
		ResY=600
		StaticDecals=False
		DynamicDecals=True
		MaxActiveDecals=10
		UnbatchedDecals=True
		DecalCullDistanceScale=0.4
		DynamicShadows=False
		LightEnvironmentShadows=False
		MotionBlur=False
		DepthOfField=True
		AmbientOcclusion=False
		Bloom=False
		bAllowLightShafts=False
		Distortion=False
		DropParticleDistortion=True
		LensFlares=False
		AllowRadialBlur=False
		bAllowSeparateTranslucency=False
		bAllowPostprocessMLAA=False
		bAllowHighQualityMaterials=False
		SkeletalMeshLODBias=1
		DetailMode=0
		MaxDrawDistanceScale=0.8
		MaxAnisotropy=0
		MaxShadowResolution=256
		MaxWholeSceneDominantShadowResolution=256
		ScreenPercentage=100.000000
		ShadowTexelsPerPixel=2.0
		bAllowWholeSceneDominantShadows=False
		bUseConservativeShadowBounds=True
		bAllowFracturedDamage=False
		FractureCullDistanceScale=0.25
		DynamicLights=False
		bAllowDropShadows=False
		CompositeDynamicLights=False
		SHSecondaryLighting=False
		bAllowFog=False
		DirectionalLightmaps=True
		bAllowParticleSystemPerfBias=True
		bAllowParticleSystemPerfThrottling=True
		PerfScalingFramerateRange=20.0
		AllowSubsurfaceScattering=False
		AllowImageReflections=False
		StaticMeshLODBias=1
		ParticleLODBias=10
		PerfScalingBias=0.2
		ShadowFilterQualityBias=-1
		MaxMultisamples=1
		FXAAQuality=0
		bAllowRagdolling=False
		SpeedTreeLODBias=2
		AllowScreenDoorFade=False
		AllowScreenDoorLODFading=False
		bUseLowQualMaterials=True
		TexturePoolSize=150
		MaterialQualityLevel=1
		SpeedTreeWind=False
		UseCinematicMipCalculations=true
		TEXTUREGROUP_World=(MinLODSize=32,MaxLODSize=256,LODBias=3,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_WorldNormalMap=(MinLODSize=32,MaxLODSize=256,LODBias=3,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_WorldSpecular=(MinLODSize=32,MaxLODSize=256,LODBias=3,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Character=(MinLODSize=64,MaxLODSize=1024,LODBias=2,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_CharacterNormalMap=(MinLODSize=64,MaxLODSize=1024,LODBias=2,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_CharacterSpecular=(MinLODSize=64,MaxLODSize=512,LODBias=2,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Weapon=(MinLODSize=64,MaxLODSize=256,LODBias=2,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_WeaponNormalMap=(MinLODSize=64,MaxLODSize=256,LODBias=2,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_WeaponSpecular=(MinLODSize=64,MaxLODSize=256,LODBias=2,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Vehicle=(MinLODSize=64,MaxLODSize=512,LODBias=2,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_VehicleNormalMap=(MinLODSize=64,MaxLODSize=512,LODBias=2,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_VehicleSpecular=(MinLODSize=64,MaxLODSize=512,LODBias=2,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Cinematic=(MinLODSize=128,MaxLODSize=256,LODBias=2,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Effects=(MinLODSize=32,MaxLODSize=256,LODBias=2,MinMagFilter=linear,MipFilter=point)
		TEXTUREGROUP_EffectsNotFiltered=(MinLODSize=32,MaxLODSize=256,LODBias=2,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Skybox=(MinLODSize=64,MaxLODSize=256,LODBias=2,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_UI=(MinLODSize=1,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_UIStreamable=(MinLODSize=1,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point,NumStreamedMips=0)
		TEXTUREGROUP_Lightmap=(MinLODSize=1,MaxLODSize=512,LODBias=3,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Shadowmap=(MinLODSize=1,MaxLODSize=512,LODBias=3,MinMagFilter=aniso,MipFilter=point,NumStreamedMips=3)
		TEXTUREGROUP_RenderTarget=(MinLODSize=1,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_MobileFlattened=(MinLODSize=1,MaxLODSize=4096,LODBias=1,MinMagFilter=linear,MipFilter=point)
		TEXTUREGROUP_ProcBuilding_Face=(MinLODSize=1,MaxLODSize=1024,LODBias=1,MinMagFilter=linear,MipFilter=point)
		TEXTUREGROUP_ProcBuilding_LightMap=(MinLODSize=1,MaxLODSize=256,LODBias=1,MinMagFilter=linear,MipFilter=point)
		TEXTUREGROUP_Terrain_Heightmap=(MinLODSize=1,MaxLODSize=4096,LODBias=0,MinMagFilter=linear,MipFilter=point)
		TEXTUREGROUP_Terrain_Weightmap=(MinLODSize=1,MaxLODSize=4096,LODBias=0,MinMagFilter=linear,MipFilter=point)
		TEXTUREGROUP_ImageBasedReflection=(MinLODSize=256,MaxLODSize=4096,LODBias=1,MinMagFilter=linear,MipFilter=linear,MipGenSettings=TMGS_Blur5)
		TEXTUREGROUP_Bokeh=(MinLODSize=1,MaxLODSize=256,LODBias=1,MinMagFilter=linear,MipFilter=linear)
		TEXTUREGROUP_NPC=(MinLODSize=64,MaxLODSize=512,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_NPCNormalMap=(MinLODSize=64,MaxLODSize=256,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_NPCSpecular=(MinLODSize=64,MaxLODSize=256,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_WorldDetail=(MinLODSize=64,MaxLODSize=256,LODBias=3,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_TitleScreenPreview=(MinLODSize=1,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)

		[SystemSettingsBucket2]
		BasedOn=SystemSettings
		MeshScreenPixelAreaThreshold=196.0
		OctreeScreenPixelAreaThreshold=392.0
		ResX=1280
		ResY=720
		StaticDecals=False
		DynamicDecals=True
		MaxActiveDecals=25
		UnbatchedDecals=True
		DecalCullDistanceScale=0.5
		DynamicShadows=False
		LightEnvironmentShadows=False
		MotionBlur=False
		DepthOfField=True
		AmbientOcclusion=False
		Bloom=False
		bAllowLightShafts=False
		Distortion=False
		DropParticleDistortion=True
		LensFlares=False
		AllowRadialBlur=False
		bAllowSeparateTranslucency=False
		bAllowPostprocessMLAA=False
		bAllowHighQualityMaterials=False
		SkeletalMeshLODBias=1
		DetailMode=0
		MaxDrawDistanceScale=0.9
		MaxAnisotropy=0
		MaxShadowResolution=512
		MaxWholeSceneDominantShadowResolution=512
		ScreenPercentage=100.000000
		ShadowTexelsPerPixel=2.0
		bAllowWholeSceneDominantShadows=False
		bUseConservativeShadowBounds=True
		bAllowFracturedDamage=False
		FractureCullDistanceScale=0.5
		DynamicLights=True
		bAllowDropShadows=True
		CompositeDynamicLights=True
		SHSecondaryLighting=False
		bAllowFog=False
		DirectionalLightmaps=True
		bAllowParticleSystemPerfBias=True
		bAllowParticleSystemPerfThrottling=True
		PerfScalingFramerateRange=20.0
		AllowSubsurfaceScattering=False
		AllowImageReflections=False
		StaticMeshLODBias=1
		ParticleLODBias=2
		PerfScalingBias=0.2
		ShadowFilterQualityBias=-1
		MaxMultisamples=1
		FXAAQuality=0
		bAllowRagdolling=False
		SpeedTreeLODBias=2
		AllowScreenDoorFade=False
		AllowScreenDoorLODFading=False
		bUseLowQualMaterials=True
		TexturePoolSize=180
		MaterialQualityLevel=1
		SpeedTreeWind=False
		UseCinematicMipCalculations=true
		TEXTUREGROUP_World=(MinLODSize=32,MaxLODSize=256,LODBias=3,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_WorldNormalMap=(MinLODSize=32,MaxLODSize=256,LODBias=3,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_WorldSpecular=(MinLODSize=32,MaxLODSize=256,LODBias=3,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Character=(MinLODSize=64,MaxLODSize=1024,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_CharacterNormalMap=(MinLODSize=64,MaxLODSize=1024,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_CharacterSpecular=(MinLODSize=64,MaxLODSize=512,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Weapon=(MinLODSize=64,MaxLODSize=256,LODBias=2,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_WeaponNormalMap=(MinLODSize=64,MaxLODSize=256,LODBias=2,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_WeaponSpecular=(MinLODSize=64,MaxLODSize=256,LODBias=2,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Vehicle=(MinLODSize=64,MaxLODSize=512,LODBias=2,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_VehicleNormalMap=(MinLODSize=64,MaxLODSize=512,LODBias=2,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_VehicleSpecular=(MinLODSize=64,MaxLODSize=512,LODBias=2,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Cinematic=(MinLODSize=128,MaxLODSize=512,LODBias=2,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Effects=(MinLODSize=32,MaxLODSize=512,LODBias=2,MinMagFilter=linear,MipFilter=point)
		TEXTUREGROUP_EffectsNotFiltered=(MinLODSize=32,MaxLODSize=512,LODBias=2,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Skybox=(MinLODSize=128,MaxLODSize=512,LODBias=2,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_UI=(MinLODSize=1,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_UIStreamable=(MinLODSize=1,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point,NumStreamedMips=0)
		TEXTUREGROUP_Lightmap=(MinLODSize=1,MaxLODSize=512,LODBias=2,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Shadowmap=(MinLODSize=1,MaxLODSize=512,LODBias=2,MinMagFilter=aniso,MipFilter=point,NumStreamedMips=3)
		TEXTUREGROUP_RenderTarget=(MinLODSize=1,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_MobileFlattened=(MinLODSize=1,MaxLODSize=4096,LODBias=0,MinMagFilter=linear,MipFilter=point)
		TEXTUREGROUP_ProcBuilding_Face=(MinLODSize=1,MaxLODSize=1024,LODBias=0,MinMagFilter=linear,MipFilter=point)
		TEXTUREGROUP_ProcBuilding_LightMap=(MinLODSize=1,MaxLODSize=256,LODBias=0,MinMagFilter=linear,MipFilter=point)
		TEXTUREGROUP_Terrain_Heightmap=(MinLODSize=1,MaxLODSize=4096,LODBias=0,MinMagFilter=linear,MipFilter=point)
		TEXTUREGROUP_Terrain_Weightmap=(MinLODSize=1,MaxLODSize=4096,LODBias=0,MinMagFilter=linear,MipFilter=point)
		TEXTUREGROUP_ImageBasedReflection=(MinLODSize=256,MaxLODSize=4096,LODBias=0,MinMagFilter=linear,MipFilter=linear,MipGenSettings=TMGS_Blur5)
		TEXTUREGROUP_Bokeh=(MinLODSize=1,MaxLODSize=256,LODBias=0,MinMagFilter=linear,MipFilter=linear)
		TEXTUREGROUP_NPC=(MinLODSize=64,MaxLODSize=512,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_NPCNormalMap=(MinLODSize=64,MaxLODSize=512,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_NPCSpecular=(MinLODSize=64,MaxLODSize=512,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_WorldDetail=(MinLODSize=32,MaxLODSize=256,LODBias=2,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_TitleScreenPreview=(MinLODSize=1,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)

		[SystemSettingsBucket3]
		BasedOn=SystemSettings
		MeshScreenPixelAreaThreshold=196.0
		OctreeScreenPixelAreaThreshold=392.0
		ResX=1280
		ResY=720
		StaticDecals=True
		DynamicDecals=True
		MaxActiveDecals=50
		UnbatchedDecals=True
		DecalCullDistanceScale=0.6
		DynamicShadows=False
		LightEnvironmentShadows=True
		MotionBlur=False
		DepthOfField=True
		AmbientOcclusion=False
		Bloom=True
		bAllowLightShafts=False
		Distortion=True
		DropParticleDistortion=True
		LensFlares=True
		AllowRadialBlur=True
		bAllowSeparateTranslucency=False
		bAllowPostprocessMLAA=False
		bAllowHighQualityMaterials=True
		SkeletalMeshLODBias=0
		DetailMode=1
		MaxDrawDistanceScale=1.0
		MaxAnisotropy=4
		MaxShadowResolution=512
		MaxWholeSceneDominantShadowResolution=1280
		ScreenPercentage=100.000000
		ShadowTexelsPerPixel=2.0
		bAllowWholeSceneDominantShadows=True
		bUseConservativeShadowBounds=False
		bAllowFracturedDamage=True
		FractureCullDistanceScale=1.0
		DynamicLights=True
		bAllowDropShadows=True
		CompositeDynamicLights=True
		SHSecondaryLighting=True
		bAllowFog=True
		DirectionalLightmaps=True
		bAllowParticleSystemPerfBias=True
		bAllowParticleSystemPerfThrottling=True
		PerfScalingFramerateRange=20.0
		AllowSubsurfaceScattering=False
		AllowImageReflections=False
		StaticMeshLODBias=0
		ParticleLODBias=1
		PerfScalingBias=0.1
		ShadowFilterQualityBias=0
		MaxMultisamples=1
		FXAAQuality=0
		bAllowRagdolling=True
		SpeedTreeLODBias=2
		AllowScreenDoorFade=False
		AllowScreenDoorLODFading=False
		bUseLowQualMaterials=False
		TexturePoolSize=225
		MaterialQualityLevel=2
		SpeedTreeWind=True
		UseCinematicMipCalculations=true
		TEXTUREGROUP_World=(MinLODSize=64,MaxLODSize=512,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_WorldNormalMap=(MinLODSize=64,MaxLODSize=512,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_WorldSpecular=(MinLODSize=64,MaxLODSize=256,LODBias=2,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Character=(MinLODSize=128,MaxLODSize=1024,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_CharacterNormalMap=(MinLODSize=128,MaxLODSize=1024,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_CharacterSpecular=(MinLODSize=128,MaxLODSize=1024,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Weapon=(MinLODSize=128,MaxLODSize=1024,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_WeaponNormalMap=(MinLODSize=128,MaxLODSize=1024,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_WeaponSpecular=(MinLODSize=128,MaxLODSize=1024,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Vehicle=(MinLODSize=64,MaxLODSize=1024,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_VehicleNormalMap=(MinLODSize=64,MaxLODSize=1024,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_VehicleSpecular=(MinLODSize=64,MaxLODSize=512,LODBias=2,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Cinematic=(MinLODSize=128,MaxLODSize=512,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Effects=(MinLODSize=128,MaxLODSize=512,LODBias=1,MinMagFilter=linear,MipFilter=point)
		TEXTUREGROUP_EffectsNotFiltered=(MinLODSize=128,MaxLODSize=512,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Skybox=(MinLODSize=256,MaxLODSize=1024,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_UI=(MinLODSize=1,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_UIStreamable=(MinLODSize=1,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point,NumStreamedMips=0)
		TEXTUREGROUP_Lightmap=(MinLODSize=1,MaxLODSize=512,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Shadowmap=(MinLODSize=1,MaxLODSize=512,LODBias=1,MinMagFilter=aniso,MipFilter=point,NumStreamedMips=3)
		TEXTUREGROUP_RenderTarget=(MinLODSize=1,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_MobileFlattened=(MinLODSize=1,MaxLODSize=4096,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_ProcBuilding_Face=(MinLODSize=1,MaxLODSize=1024,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_ProcBuilding_LightMap=(MinLODSize=1,MaxLODSize=256,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Terrain_Heightmap=(MinLODSize=1,MaxLODSize=4096,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Terrain_Weightmap=(MinLODSize=1,MaxLODSize=4096,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_ImageBasedReflection=(MinLODSize=256,MaxLODSize=4096,LODBias=0,MinMagFilter=aniso,MipFilter=linear,MipGenSettings=TMGS_Blur5)
		TEXTUREGROUP_Bokeh=(MinLODSize=1,MaxLODSize=256,LODBias=0,MinMagFilter=linear,MipFilter=linear)
		TEXTUREGROUP_NPC=(MinLODSize=64,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_NPCNormalMap=(MinLODSize=64,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_NPCSpecular=(MinLODSize=64,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_WorldDetail=(MinLODSize=128,MaxLODSize=512,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_TitleScreenPreview=(MinLODSize=1,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)

		[SystemSettingsBucket4]
		BasedOn=SystemSettings
		MeshScreenPixelAreaThreshold=144.0
		OctreeScreenPixelAreaThreshold=288.0
		ResX=1280
		ResY=720
		StaticDecals=True
		DynamicDecals=True
		MaxActiveDecals=50
		UnbatchedDecals=True
		DecalCullDistanceScale=0.8
		DynamicShadows=True
		LightEnvironmentShadows=True
		MotionBlur=False
		DepthOfField=True
		AmbientOcclusion=False
		Bloom=True
		bAllowLightShafts=True
		Distortion=True
		DropParticleDistortion=False
		LensFlares=True
		AllowRadialBlur=True
		bAllowSeparateTranslucency=False
		bAllowPostprocessMLAA=False
		bAllowHighQualityMaterials=True
		SkeletalMeshLODBias=0
		DetailMode=2
		MaxDrawDistanceScale=1.1
		MaxAnisotropy=4
		MaxShadowResolution=512
		MaxWholeSceneDominantShadowResolution=2048
		ScreenPercentage=100.000000
		ShadowTexelsPerPixel=2.0
		bAllowWholeSceneDominantShadows=True
		bUseConservativeShadowBounds=False
		bAllowFracturedDamage=True
		FractureCullDistanceScale=1.5
		DynamicLights=True
		bAllowDropShadows=True
		CompositeDynamicLights=True
		SHSecondaryLighting=True
		bAllowFog=True
		DirectionalLightmaps=True
		bAllowParticleSystemPerfBias=True
		bAllowParticleSystemPerfThrottling=True
		PerfScalingFramerateRange=20.0
		AllowSubsurfaceScattering=False
		AllowImageReflections=False
		StaticMeshLODBias=0
		ParticleLODBias=0
		PerfScalingBias=0.0
		ShadowFilterQualityBias=0
		MaxMultisamples=1
		FXAAQuality=0
		bAllowRagdolling=True
		SpeedTreeLODBias=1
		AllowScreenDoorFade=True
		AllowScreenDoorLODFading=False
		bUseLowQualMaterials=False
		TexturePoolSize=450
		MaterialQualityLevel=0
		SpeedTreeWind=True
		UseCinematicMipCalculations=true
		TEXTUREGROUP_World=(MinLODSize=64,MaxLODSize=512,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_WorldNormalMap=(MinLODSize=64,MaxLODSize=1024,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_WorldSpecular=(MinLODSize=64,MaxLODSize=512,LODBias=2,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Character=(MinLODSize=128,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_CharacterNormalMap=(MinLODSize=128,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_CharacterSpecular=(MinLODSize=128,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Weapon=(MinLODSize=128,MaxLODSize=2048,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_WeaponNormalMap=(MinLODSize=128,MaxLODSize=2048,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_WeaponSpecular=(MinLODSize=128,MaxLODSize=2048,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Vehicle=(MinLODSize=128,MaxLODSize=1024,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_VehicleNormalMap=(MinLODSize=128,MaxLODSize=1024,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_VehicleSpecular=(MinLODSize=128,MaxLODSize=1024,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Cinematic=(MinLODSize=256,MaxLODSize=512,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Effects=(MinLODSize=256,MaxLODSize=512,LODBias=1,MinMagFilter=linear,MipFilter=point)
		TEXTUREGROUP_EffectsNotFiltered=(MinLODSize=256,MaxLODSize=512,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Skybox=(MinLODSize=256,MaxLODSize=1024,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_UI=(MinLODSize=1,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_UIStreamable=(MinLODSize=1,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point,NumStreamedMips=0)
		TEXTUREGROUP_Lightmap=(MinLODSize=1,MaxLODSize=1024,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Shadowmap=(MinLODSize=1,MaxLODSize=1024,LODBias=1,MinMagFilter=aniso,MipFilter=point,NumStreamedMips=3)
		TEXTUREGROUP_RenderTarget=(MinLODSize=1,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_MobileFlattened=(MinLODSize=1,MaxLODSize=4096,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_ProcBuilding_Face=(MinLODSize=1,MaxLODSize=1024,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_ProcBuilding_LightMap=(MinLODSize=1,MaxLODSize=256,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Terrain_Heightmap=(MinLODSize=1,MaxLODSize=4096,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Terrain_Weightmap=(MinLODSize=1,MaxLODSize=4096,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_ImageBasedReflection=(MinLODSize=256,MaxLODSize=4096,LODBias=0,MinMagFilter=aniso,MipFilter=linear,MipGenSettings=TMGS_Blur5)
		TEXTUREGROUP_Bokeh=(MinLODSize=1,MaxLODSize=256,LODBias=0,MinMagFilter=linear,MipFilter=linear)
		TEXTUREGROUP_NPC=(MinLODSize=128,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_NPCNormalMap=(MinLODSize=128,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_NPCSpecular=(MinLODSize=128,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_WorldDetail=(MinLODSize=64,MaxLODSize=1024,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_TitleScreenPreview=(MinLODSize=1,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)

		[SystemSettingsBucket5]
		BasedOn=SystemSettings
		MeshScreenPixelAreaThreshold=100.0
		OctreeScreenPixelAreaThreshold=200.0
		ResX=1280
		ResY=720
		StaticDecals=True
		DynamicDecals=True
		MaxActiveDecals=50
		UnbatchedDecals=True
		DecalCullDistanceScale=1.0
		DynamicShadows=True
		LightEnvironmentShadows=True
		MotionBlur=False
		DepthOfField=True
		AmbientOcclusion=True
		Bloom=True
		bAllowLightShafts=True
		Distortion=True
		DropParticleDistortion=False
		LensFlares=True
		AllowRadialBlur=True
		bAllowSeparateTranslucency=False
		bAllowPostprocessMLAA=False
		bAllowHighQualityMaterials=True
		SkeletalMeshLODBias=0
		DetailMode=2
		MaxDrawDistanceScale=1.2
		MaxAnisotropy=16
		MaxShadowResolution=512
		MaxWholeSceneDominantShadowResolution=4096
		ScreenPercentage=100.000000
		ShadowTexelsPerPixel=2.0
		bAllowWholeSceneDominantShadows=True
		bUseConservativeShadowBounds=False
		bAllowFracturedDamage=True
		FractureCullDistanceScale=2.0
		DynamicLights=True
		bAllowDropShadows=True
		CompositeDynamicLights=True
		SHSecondaryLighting=True
		bAllowFog=True
		DirectionalLightmaps=True
		bAllowParticleSystemPerfBias=True
		bAllowParticleSystemPerfThrottling=True
		PerfScalingFramerateRange=50.0
		AllowSubsurfaceScattering=False
		AllowImageReflections=False
		StaticMeshLODBias=0
		ParticleLODBias=0
		PerfScalingBias=0.0
		ShadowFilterQualityBias=1
		MaxMultisamples=4
		FXAAQuality=0
		bAllowRagdolling=True
		SpeedTreeLODBias=0
		AllowScreenDoorFade=True
		AllowScreenDoorLODFading=False
		bUseLowQualMaterials=False
		TexturePoolSize=900
		MaterialQualityLevel=0
		SpeedTreeWind=True
		UseCinematicMipCalculations=FALSE
		TEXTUREGROUP_World=(MinLODSize=64,MaxLODSize=512,LODBias=1,MaxLODSizeTexturePack=2048,LODBiasTexturePack=0,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_WorldNormalMap=(MinLODSize=64,MaxLODSize=1024,LODBias=1,MaxLODSizeTexturePack=2048,LODBiasTexturePack=0,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_WorldSpecular=(MinLODSize=64,MaxLODSize=512,LODBias=1,MaxLODSizeTexturePack=2048,LODBiasTexturePack=0,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_Character=(MinLODSize=256,MaxLODSize=512,LODBias=0,MaxLODSizeTexturePack=2048,LODBiasTexturePack=0,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_CharacterNormalMap=(MinLODSize=256,MaxLODSize=512,LODBias=0,MaxLODSizeTexturePack=2048,LODBiasTexturePack=0,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_CharacterSpecular=(MinLODSize=256,MaxLODSize=512,LODBias=0,MaxLODSizeTexturePack=2048,LODBiasTexturePack=0,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_Weapon=(MinLODSize=256,MaxLODSize=512,LODBias=1,MaxLODSizeTexturePack=2048,LODBiasTexturePack=0,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_WeaponNormalMap=(MinLODSize=256,MaxLODSize=512,LODBias=1,MaxLODSizeTexturePack=2048,LODBiasTexturePack=0,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_WeaponSpecular=(MinLODSize=256,MaxLODSize=512,LODBias=1,MaxLODSizeTexturePack=2048,LODBiasTexturePack=0,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_Vehicle=(MinLODSize=256,MaxLODSize=2048,LODBias=1,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_VehicleNormalMap=(MinLODSize=256,MaxLODSize=2048,LODBias=1,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_VehicleSpecular=(MinLODSize=256,MaxLODSize=2048,LODBias=1,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_Cinematic=(MinLODSize=256,MaxLODSize=1024,LODBias=1,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_Effects=(MinLODSize=256,MaxLODSize=1024,LODBias=1,MinMagFilter=linear,MipFilter=linear)
		TEXTUREGROUP_EffectsNotFiltered=(MinLODSize=256,MaxLODSize=512,LODBias=0,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_Skybox=(MinLODSize=512,MaxLODSize=2048,LODBias=0,MaxLODSizeTexturePack=4096,LODBiasTexturePack=0,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_UI=(MinLODSize=1,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_UIStreamable=(MinLODSize=1,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point,NumStreamedMips=0)
		TEXTUREGROUP_Lightmap=(MinLODSize=1,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_Shadowmap=(MinLODSize=1,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=linear,NumStreamedMips=3)
		TEXTUREGROUP_RenderTarget=(MinLODSize=1,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_MobileFlattened=(MinLODSize=1,MaxLODSize=4096,LODBias=0,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_ProcBuilding_Face=(MinLODSize=1,MaxLODSize=1024,LODBias=0,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_ProcBuilding_LightMap=(MinLODSize=1,MaxLODSize=256,LODBias=0,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_Terrain_Heightmap=(MinLODSize=1,MaxLODSize=4096,LODBias=0,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_Terrain_Weightmap=(MinLODSize=1,MaxLODSize=4096,LODBias=0,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_ImageBasedReflection=(MinLODSize=256,MaxLODSize=4096,LODBias=0,MinMagFilter=aniso,MipFilter=linear,MipGenSettings=TMGS_Blur5)
		TEXTUREGROUP_Bokeh=(MinLODSize=1,MaxLODSize=256,LODBias=0,MinMagFilter=linear,MipFilter=linear)
		TEXTUREGROUP_NPC=(MinLODSize=256,MaxLODSize=512,LODBias=0,MaxLODSizeTexturePack=2048,LODBiasTexturePack=0,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_NPCNormalMap=(MinLODSize=256,MaxLODSize=512,LODBias=0,MaxLODSizeTexturePack=2048,LODBiasTexturePack=0,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_NPCSpecular=(MinLODSize=256,MaxLODSize=512,LODBias=0,MaxLODSizeTexturePack=2048,LODBiasTexturePack=0,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_WorldDetail=(MinLODSize=64,MaxLODSize=1024,LODBias=0,MaxLODSizeTexturePack=2048,LODBiasTexturePack=0,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_TitleScreenPreview=(MinLODSize=1,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)

		[SystemSettingsScreenshot]
		BasedOn=SystemSettings
		MaxAnisotropy=16
		ShadowFilterQualityBias=1
		MinShadowResolution=16
		ShadowFadeResolution=1
		MinPreShadowResolution=16
		PreShadowFadeResolution=1
		ShadowTexelsPerPixel=4.0f
		PreShadowResolutionFactor=1.0
		MaxShadowResolution=4096
		MaxWholeSceneDominantShadowResolution=4096
		CompositeDynamicLights=FALSE
		TEXTUREGROUP_World=(MinLODSize=1,MaxLODSize=4096,LODBias=-1000,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_WorldNormalMap=(MinLODSize=1,MaxLODSize=4096,LODBias=-1000,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_WorldSpecular=(MinLODSize=1,MaxLODSize=4096,LODBias=-1000,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_Character=(MinLODSize=1,MaxLODSize=4096,LODBias=-1000,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_CharacterNormalMap=(MinLODSize=1,MaxLODSize=4096,LODBias=-1000,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_CharacterSpecular=(MinLODSize=1,MaxLODSize=4096,LODBias=-1000,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_Weapon=(MinLODSize=1,MaxLODSize=4096,LODBias=-1000,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_WeaponNormalMap=(MinLODSize=1,MaxLODSize=4096,LODBias=-1000,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_WeaponSpecular=(MinLODSize=1,MaxLODSize=4096,LODBias=-1000,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_Vehicle=(MinLODSize=1,MaxLODSize=4096,LODBias=-1000,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_VehicleNormalMap=(MinLODSize=1,MaxLODSize=4096,LODBias=-1000,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_VehicleSpecular=(MinLODSize=1,MaxLODSize=4096,LODBias=-1000,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_Cinematic=(MinLODSize=1,MaxLODSize=4096,LODBias=-1000,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_Effects=(MinLODSize=1,MaxLODSize=4096,LODBias=-1000,MinMagFilter=linear,MipFilter=linear)
		TEXTUREGROUP_EffectsNotFiltered=(MinLODSize=1,MaxLODSize=4096,LODBias=-1000,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_Skybox=(MinLODSize=1,MaxLODSize=4096,LODBias=-1000,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_UI=(MinLODSize=1,MaxLODSize=4096,LODBias=-1000,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_Lightmap=(MinLODSize=1,MaxLODSize=4096,LODBias=-1000,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_Shadowmap=(MinLODSize=1,MaxLODSize=4096,LODBias=-1000,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_RenderTarget=(MinLODSize=1,MaxLODSize=4096,LODBias=-1000,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_MobileFlattened=(MinLODSize=1,MaxLODSize=4096,LODBias=-1000,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_ProcBuilding_Face=(MinLODSize=1,MaxLODSize=4096,LODBias=-1000,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_ProcBuilding_LightMap=(MinLODSize=1,MaxLODSize=4096,LODBias=-1000,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_Terrain_Heightmap=(MinLODSize=1,MaxLODSize=4096,LODBias=-1000,MinMagFilter=aniso,MipFilter=linear)
		TEXTUREGROUP_Terrain_Weightmap=(MinLODSize=1,MaxLODSize=4096,LODBias=-1000,MinMagFilter=aniso,MipFilter=linear)

		[SystemSettingsEditor]
		BasedOn=SystemSettingsBucket5

		[SystemSettingsSplitScreen2]
		BasedOn=SystemSettings
		bAllowWholeSceneDominantShadows=False
		bAllowLightShafts=False
		DetailMode=1

		[SystemSettingsMobile]
		BasedOn=SystemSettings
		Fullscreen=True
		DirectionalLightmaps=False
		DynamicLights=False
		SHSecondaryLighting=False
		StaticDecals=True
		DynamicDecals=False
		UnbatchedDecals=False
		MotionBlur=FALSE
		MotionBlurPause=FALSE
		DepthOfField=FALSE
		AmbientOcclusion=FALSE
		Bloom=FALSE
		Distortion=FALSE
		FilteredDistortion=FALSE
		DropParticleDistortion=TRUE
		FloatingPointRenderTargets=FALSE
		MaxAnisotropy=2
		bAllowLightShafts=FALSE
		MobileModShadows=False
		MobileClearDepthBetweenDPG=False
		MaxFilterBlurSampleCount=4
		DynamicShadows=False
		MobileMaxMemory=300
		MobileLandscapeLodBias=0
		AllowRadialBlur=False

		[SystemSettingsMobilePreviewer]
		BasedOn=SystemSettingsMobile
		Fullscreen=False

		[SystemSettingsMobileTextureBias]
		BasedOn=SystemSettingsMobile
		TEXTUREGROUP_World=(MinLODSize=1,MaxLODSize=4096,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_WorldNormalMap=(MinLODSize=1,MaxLODSize=4096,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_WorldSpecular=(MinLODSize=1,MaxLODSize=4096,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Character=(MinLODSize=1,MaxLODSize=4096,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_CharacterNormalMap=(MinLODSize=1,MaxLODSize=4096,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_CharacterSpecular=(MinLODSize=1,MaxLODSize=4096,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Weapon=(MinLODSize=1,MaxLODSize=4096,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_WeaponNormalMap=(MinLODSize=1,MaxLODSize=4096,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_WeaponSpecular=(MinLODSize=1,MaxLODSize=4096,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Vehicle=(MinLODSize=1,MaxLODSize=4096,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_VehicleNormalMap=(MinLODSize=1,MaxLODSize=4096,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_VehicleSpecular=(MinLODSize=1,MaxLODSize=4096,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Cinematic=(MinLODSize=1,MaxLODSize=4096,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Effects=(MinLODSize=1,MaxLODSize=4096,LODBias=1,MinMagFilter=linear,MipFilter=point)
		TEXTUREGROUP_EffectsNotFiltered=(MinLODSize=1,MaxLODSize=4096,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Skybox=(MinLODSize=1,MaxLODSize=4096,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_UI=(MinLODSize=1,MaxLODSize=4096,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Lightmap=(MinLODSize=1,MaxLODSize=4096,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Shadowmap=(MinLODSize=1,MaxLODSize=4096,LODBias=1,MinMagFilter=aniso,MipFilter=point,NumStreamedMips=3)
		TEXTUREGROUP_RenderTarget=(MinLODSize=1,MaxLODSize=4096,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_MobileFlattened=(MinLODSize=1,MaxLODSize=4096,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_ProcBuilding_Face=(MinLODSize=1,MaxLODSize=1024,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_ProcBuilding_LightMap=(MinLODSize=1,MaxLODSize=256,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Terrain_Heightmap=(MinLODSize=1,MaxLODSize=4096,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Terrain_Weightmap=(MinLODSize=1,MaxLODSize=4096,LODBias=1,MinMagFilter=aniso,MipFilter=point)

		[SystemSettingsAndroid]
		BasedOn=SystemSettingsMobileTextureBias

		[SystemSettingsAndroid_Performance1_MemoryLow]
		BasedOn=SystemSettingsMobileTextureBias
		MobileFeatureLevel=1
		MobileFog=False
		MobileSpecular=False
		MobileBumpOffset=False
		MobileNormalMapping=False
		MobileEnvMapping=False
		MobileRimLighting=False
		MobileContentScaleFactor=0.9375

		[SystemSettingsAndroid_Performance2_MemoryLow]
		BasedOn=SystemSettingsMobileTextureBias
		MobileBumpOffset=False
		MobileNormalMapping=False
		MobileContentScaleFactor=0.9375

		[SystemSettingsAndroid_Performance1_Memory1024]
		BasedOn=SystemSettingsMobile
		MobileFeatureLevel=1
		MobileFog=False
		MobileSpecular=False
		MobileBumpOffset=False
		MobileNormalMapping=False
		MobileEnvMapping=False
		MobileRimLighting=False
		MobileContentScaleFactor=0.9375

		[SystemSettingsAndroid_Performance2_Memory1024]
		BasedOn=SystemSettingsMobile
		MobileBumpOffset=False
		MobileNormalMapping=False
		MobileContentScaleFactor=0.9375

		[SystemSettingsFlash]
		BasedOn=SystemSettingsMobileTextureBias
		MotionBlur=FALSE
		MotionBlurPause=FALSE
		DepthOfField=FALSE
		AmbientOcclusion=FALSE
		Bloom=FALSE
		Distortion=FALSE
		FilteredDistortion=FALSE
		bAllowLightShafts=FALSE
		MobileModShadows=True
		DynamicShadows=True
		MobileClearDepthBetweenDPG=True
		DirectionalLightmaps=False
		MobileHeightFog=False

		[SystemSettingsIPhone]
		BasedOn=SystemSettingsMobileTextureBias
		bMobileUsingHighResolutionTiming=False

		[SystemSettingsIPhone3GS]
		BasedOn=SystemSettingsMobileTextureBias
		LensFlares=False
		DetailMode=1
		MobileEnableMSAA=True
		MobileMaxMemory=100
		bMobileUsingHighResolutionTiming=False
		MobileLandscapeLodBias=2

		[SystemSettingsIPhone4]
		BasedOn=SystemSettingsMobile
		MobileContentScaleFactor=2.0
		LensFlares=False
		bMobileUsingHighResolutionTiming=False
		MobileLandscapeLodBias=1

		[SystemSettingsIPhone4S]
		BasedOn=SystemSettingsMobile
		MobileEnableMSAA=True
		bAllowLightShafts=True
		MobileModShadows=True
		DynamicShadows=False
		ShadowDepthBias=0.025
		MobileContentScaleFactor=2.0
		MaxShadowResolution=256
		MobileShadowTextureResolution=256

		[SystemSettingsIPhone5]
		BasedOn=SystemSettingsMobile
		MobileEnableMSAA=True
		bAllowLightShafts=True
		MobileModShadows=True
		DynamicShadows=False
		ShadowDepthBias=0.025
		MobileContentScaleFactor=2.0
		MaxShadowResolution=256
		MobileShadowTextureResolution=1024
		AllowRadialBlur=True

		[SystemSettingsIPodTouch4]
		BasedOn=SystemSettingsMobileTextureBias
		MobileContentScaleFactor=2.0
		LensFlares=False
		MobileMaxMemory=100
		bMobileUsingHighResolutionTiming=False
		MobileLandscapeLodBias=2

		[SystemSettingsIPodTouch5]
		BasedOn=SystemSettingsMobile
		MobileEnableMSAA=True
		bAllowLightShafts=True
		MobileModShadows=True
		DynamicShadows=False
		ShadowDepthBias=0.025
		MobileContentScaleFactor=2.0
		MaxShadowResolution=256
		MobileShadowTextureResolution=256

		[SystemSettingsIPad]
		BasedOn=SystemSettingsMobileTextureBias
		MobileFeatureLevel=1
		MobileFog=False
		MobileSpecular=False
		MobileBumpOffset=False
		MobileNormalMapping=False
		MobileEnvMapping=False
		MobileRimLighting=False
		MobileMaxMemory=100
		bMobileUsingHighResolutionTiming=False
		MobileLandscapeLodBias=1
		MobileContentScaleFactor=0.9375

		[SystemSettingsIPad2]
		BasedOn=SystemSettingsMobile
		MobileEnableMSAA=False
		bAllowLightShafts=True
		MobileModShadows=True
		DynamicShadows=False
		ShadowDepthBias=0.016
		MobileContentScaleFactor=1.0
		MaxShadowResolution=256
		MobileShadowTextureResolution=256

		[SystemSettingsIPad3]
		BasedOn=SystemSettingsMobile
		MobileEnableMSAA=False
		bAllowLightShafts=True
		MobileModShadows=True
		DynamicShadows=True
		ShadowDepthBias=0.016
		MobileContentScaleFactor=1.40625
		MaxShadowResolution=256
		MobileShadowTextureResolution=256
		MobileMaxMemory=500

		[SystemSettingsIPad4]
		BasedOn=SystemSettingsMobile
		MobileEnableMSAA=False
		bAllowLightShafts=True
		MobileModShadows=True
		DynamicShadows=True
		ShadowDepthBias=0.016
		MobileContentScaleFactor=2.0
		MaxShadowResolution=512
		MobileShadowTextureResolution=512
		MobileMaxMemory=500
		AllowRadialBlur=True

		[SystemSettingsIPadMini]
		BasedOn=SystemSettingsMobile
		MobileEnableMSAA=False
		bAllowLightShafts=True
		MobileModShadows=True
		DynamicShadows=False
		ShadowDepthBias=0.016
		MobileContentScaleFactor=1.0
		MaxShadowResolution=256
		MobileShadowTextureResolution=256

		[SystemSettingsIPad2_Detail]
		BasedOn=SystemSettingsIPad2

		[Configuration]

		[OpenAutomateBenchmarks]
		Benchmark=NightAndDayMap
		Benchmark=DM-Deck?CauseEvent=FlyThrough

		[TextureSettingsSpectator]
		TEXTUREGROUP_World=(MinLODSize=256,MaxLODSize=512,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_WorldNormalMap=(MinLODSize=512,MaxLODSize=1024,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_WorldSpecular=(MinLODSize=256,MaxLODSize=512,LODBias=2,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Character=(MinLODSize=256,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_CharacterNormalMap=(MinLODSize=256,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_CharacterSpecular=(MinLODSize=256,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Weapon=(MinLODSize=256,MaxLODSize=2048,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_WeaponNormalMap=(MinLODSize=256,MaxLODSize=2048,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_WeaponSpecular=(MinLODSize=256,MaxLODSize=2048,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Vehicle=(MinLODSize=256,MaxLODSize=2048,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_VehicleNormalMap=(MinLODSize=512,MaxLODSize=2048,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_VehicleSpecular=(MinLODSize=256,MaxLODSize=2048,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Cinematic=(MinLODSize=256,MaxLODSize=1024,LODBias=1,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Effects=(MinLODSize=256,MaxLODSize=1024,LODBias=1,MinMagFilter=linear,MipFilter=point)
		TEXTUREGROUP_EffectsNotFiltered=(MinLODSize=256,MaxLODSize=512,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Skybox=(MinLODSize=512,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_UI=(MinLODSize=1,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_UIStreamable=(MinLODSize=1,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point,NumStreamedMips=0)
		TEXTUREGROUP_Lightmap=(MinLODSize=1,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Shadowmap=(MinLODSize=64,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point,NumStreamedMips=3)
		TEXTUREGROUP_RenderTarget=(MinLODSize=1,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_MobileFlattened=(MinLODSize=1,MaxLODSize=4096,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_ProcBuilding_Face=(MinLODSize=1,MaxLODSize=1024,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_ProcBuilding_LightMap=(MinLODSize=1,MaxLODSize=256,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Terrain_Heightmap=(MinLODSize=1,MaxLODSize=4096,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_Terrain_Weightmap=(MinLODSize=1,MaxLODSize=4096,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_ImageBasedReflection=(MinLODSize=256,MaxLODSize=4096,LODBias=0,MinMagFilter=aniso,MipFilter=linear,MipGenSettings=TMGS_Blur5)
		TEXTUREGROUP_Bokeh=(MinLODSize=1,MaxLODSize=256,LODBias=0,MinMagFilter=linear,MipFilter=linear)
		TEXTUREGROUP_NPC=(MinLODSize=256,MaxLODSize=512,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_NPCNormalMap=(MinLODSize=256,MaxLODSize=512,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_NPCSpecular=(MinLODSize=256,MaxLODSize=512,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_WorldDetail=(MinLODSize=512,MaxLODSize=1024,LODBias=0,MinMagFilter=aniso,MipFilter=point)
		TEXTUREGROUP_TitleScreenPreview=(MinLODSize=1,MaxLODSize=2048,LODBias=0,MinMagFilter=aniso,MipFilter=point)

		[IniVersion]
		0=1540835099.000000
		1=1540929428.000000

		[SettingsCheck]
		Initialized=True


		`
		return chaosSystemSettings.replace(/\s\s\s/g, "\n").replace(/\s/g, "\n");
	}
}