let chaosSystemSettings = {
	MaxActiveDecals: 10,
	GameSettingsVersion: -1,
	StaticDecals: false,
	DynamicDecals: true,
	UnbatchedDecals: true,
	DecalCullDistanceScale: 0.400000,
	DynamicLights: false,
	DynamicShadows: false,
	LightEnvironmentShadows: false,
	CompositeDynamicLights: false,
	SHSecondaryLighting: false,
	DirectionalLightmaps: true,
	MotionBlur: false,
	MotionBlurPause: true,
	MotionBlurSkinning: 1,
	DepthOfField: true,
	AmbientOcclusion: false,
	Bloom: false,
	bAllowLightShafts: false,
	Distortion: false,
	FilteredDistortion: true,
	DropParticleDistortion: true,
	bAllowDownsampledTranslucency: false,
	SpeedTreeLeaves: true,
	SpeedTreeFronds: true,
	OnlyStreamInTextures: false,
	LensFlares: false,
	FogVolumes: true,
	FloatingPointRenderTargets: true,
	OneFrameThreadLag: true,
	UseVsync: false,
	AllowDoubleRenderFrames: false,
	ModulatedShadowStartFadeDistance: 0.000000,
	ModulatedShadowFullyFadeDistance: 0.000000,
	VsyncPresentInterval: 1,
	UseCinematicMipCalculations: true,
	bUseTripleBuffering: false,
	UpscaleScreenPercentage: true,
	Fullscreen: true,
	FullscreenWindowed: false,
	MeshScreenPixelAreaThreshold: 256.000000,
	OctreeScreenPixelAreaThreshold: 512.000000,
	AllowOpenGL: false,
	AllowRadialBlur: false,
	UseDX11: true,
	UseD3D11Beta: false,
	bAllowTexturePack: true,
	AllowSubsurfaceScattering: false,
	AllowImageReflections: false,
	AllowImageReflectionShadowing: true,
	bAllowSeparateTranslucency: false,
	bAllowPostprocessMLAA: false,
	bAllowHighQualityMaterials: false,
	MaxFilterBlurSampleCount: 16,
	SkeletalMeshLODBias: 1,
	ParticleLODBias: 10,
	DetailMode: 0,
	MaxDrawDistanceScale: 0.800000,
	ShadowFilterQualityBias: -1,
	MaxAnisotropy: 0,
	MaxMultisamples: 1,
	bAllowD3D9MSAA: false,
	bAllowTemporalAA: false,
	TemporalAA_MinDepth: 500.000000,
	TemporalAA_StartDepthVelocityScale: 100.000000,
	MinShadowResolution: 32,
	MinPreShadowResolution: 8,
	MaxShadowResolution: 256,
	MobileShadowTextureResolution: 1120,
	MaxWholeSceneDominantShadowResolution: 256,
	ShadowFadeResolution: 128,
	PreShadowFadeResolution: 16,
	ShadowFadeExponent: 0.250000,
	ResX: 1920,
	ResY: 1080,
	ScreenPercentage: 100.000000,
	SceneCaptureStreamingMultiplier: 1.000000,
	ShadowTexelsPerPixel: 2.000000,
	PreShadowResolutionFactor: 0.500000,
	bEnableBranchingPCFShadows: false,
	bAllowHardwareShadowFiltering: false,
	TessellationAdaptivePixelsPerTriangle: 48.000000,
	bEnableForegroundShadowsOnWorld: false,
	bEnableForegroundSelfShadowing: false,
	bAllowWholeSceneDominantShadows: false,
	bUseConservativeShadowBounds: true,
	ShadowFilterRadius: 2.000000,
	ShadowDepthBias: 0.012000,
	PerObjectShadowTransition: 60.000000,
	PerSceneShadowTransition: 600.000000,
	CSMSplitPenumbraScale: 0.500000,
	CSMSplitSoftTransitionDistanceScale: 4.000000,
	CSMSplitDepthBiasScale: 0.500000,
	CSMMinimumFOV: 40.000000,
	CSMFOVRoundFactor: 4.000000,
	UnbuiltWholeSceneDynamicShadowRadius: 20000.000000,
	UnbuiltNumWholeSceneDynamicShadowCascades: 3,
	WholeSceneShadowUnbuiltInteractionThreshold: 50,
	bAllowFracturedDamage: true,
	NumFracturedPartsScale: 1.000000,
	FractureDirectSpawnChanceScale: 1.000000,
	FractureRadialSpawnChanceScale: 1.000000,
	FractureCullDistanceScale: 1.000000,
	bForceCPUAccessToGPUSkinVerts: false,
	bDisableSkeletalInstanceWeights: false,
	HighPrecisionGBuffers: false,
	AllowSecondaryDisplays: false,
	SecondaryDisplayMaximumWidth: 1280,
	SecondaryDisplayMaximumHeight: 720,
	AllowLogitechLedSdk: true,
	AllowPerFrameSleep: true,
	AllowPerFrameYield: true,
	MobileFeatureLevel: 0,
	MobileFog: true,
	MobileHeightFog: false,
	MobileSpecular: true,
	MobileBumpOffset: true,
	MobileNormalMapping: true,
	MobileEnvMapping: true,
	MobileRimLighting: true,
	MobileColorBlending: true,
	MobileColorGrading: false,
	MobileVertexMovement: true,
	MobileOcclusionQueries: false,
	MobileGlobalGammaCorrection: false,
	MobileAllowGammaCorrectionWorldOverride: true,
	MobileAllowDepthPrePass: false,
	MobileGfxGammaCorrection: false,
	MobileLODBias: -0.5,
	MobileBoneCount: 75,
	MobileBoneWeightCount: 2,
	MobileUsePreprocessedShaders: true,
	MobileFlashRedForUncachedShaders: false,
	MobileWarmUpPreprocessedShaders: true,
	MobileCachePreprocessedShaders: false,
	MobileProfilePreprocessedShaders: false,
	MobileUseCPreprocessorOnShaders: true,
	MobileLoadCPreprocessedShaders: true,
	MobileSharePixelShaders: true,
	MobileShareVertexShaders: true,
	MobileShareShaderPrograms: true,
	MobileEnableMSAA: false,
	MobileContentScaleFactor: 1.0,
	MobileVertexScratchBufferSize: 150,
	MobileIndexScratchBufferSize: 10,
	MobileLightShaftScale: 2.0,
	MobileLightShaftFirstPass: 0.5,
	MobileLightShaftSecondPass: 1.0,
	MobileModShadows: true,
	MobileTiltShift: false,
	MobileMaxMemory: 300,
	MobilePostProcessBlurAmount: 32.0,
	bMobileUsingHighResolutionTiming: true,
	MobileTiltShiftPosition: 0.5,
	MobileTiltShiftFocusWidth: 0.3,
	MobileTiltShiftTransitionWidth: 0.5,
	MobileMaxShadowRange: 500.0,
	MobileBloomTint: {R: 1.0, G: 0.75, B: 0.0, A: 1.0},
	MobileClearDepthBetweenDPG: false,
	MobileSceneDepthResolveForShadows: true,
	MobileLandscapeLodBias: 0,
	MobileUseShaderGroupForStartupObjects: false,
	MobileMinimizeFogShaders: false,
	MobileFXAAQuality: 0,
	ApexLODResourceBudget: 1000000000000000000000.0,
	ApexDestructionMaxChunkIslandCount: 2500,
	ApexDestructionMaxShapeCount: 0,
	ApexDestructionMaxChunkSeparationLOD: 1.0,
	ApexDestructionMaxActorCreatesPerFrame: -1,
	ApexDestructionMaxFracturesProcessedPerFrame: -1,
	ApexDestructionSortByBenefit: true,
	ApexGRBEnable: false,
	ApexGRBGPUMemSceneSize: 128,
	ApexGRBGPUMemTempDataSize: 128,
	ApexGRBMeshCellSize: 7.5,
	ApexGRBNonPenSolverPosIterCount: 9,
	ApexGRBFrictionSolverPosIterCount: 3,
	ApexGRBFrictionSolverVelIterCount: 3,
	ApexGRBSkinWidth: 0.025,
	ApexGRBMaxLinearAcceleration: 1000000.0,
	bEnableParallelAPEXClothingFetch: true,
	bApexClothingAsyncFetchResults: false,
	ApexClothingAvgSimFrequencyWindow: 60,
	ApexClothingAllowAsyncCooking: true,
	ApexClothingAllowApexWorkBetweenSubsteps: false,
	TargetFrameRate: 60,
	TEXTUREGROUP_World: {MinLODSize: 32, MaxLODSize: 256, MaxLODSizeTexturePack: 256, LODBias: 3, LODBiasTexturePack: 3, MinMagFilter: "Aniso", MipFilter: "Point", MipGenSettings: "TMGS_SimpleAverage"},
	TEXTUREGROUP_WorldNormalMap: {MinLODSize: 32, MaxLODSize: 256, MaxLODSizeTexturePack: 256, LODBias: 3, LODBiasTexturePack: 3, MinMagFilter: "Aniso", MipFilter: "Point", MipGenSettings: "TMGS_SimpleAverage"},
	TEXTUREGROUP_WorldSpecular: {MinLODSize: 32, MaxLODSize: 256, MaxLODSizeTexturePack: 256, LODBias: 3, LODBiasTexturePack: 3, MinMagFilter: "Aniso", MipFilter: "Point", MipGenSettings: "TMGS_SimpleAverage"},
	TEXTUREGROUP_Character: {MinLODSize: 64, MaxLODSize: 512, MaxLODSizeTexturePack: 1024, LODBias: 2, LODBiasTexturePack: 2, MinMagFilter: "Aniso", MipFilter: "Point", MipGenSettings: "TMGS_SimpleAverage"},
	TEXTUREGROUP_CharacterNormalMap: {MinLODSize: 64, MaxLODSize: 512, MaxLODSizeTexturePack: 1024, LODBias: 2, LODBiasTexturePack: 2, MinMagFilter: "Aniso", MipFilter: "Point", MipGenSettings: "TMGS_SimpleAverage"},
	TEXTUREGROUP_CharacterSpecular: {MinLODSize: 64, MaxLODSize: 512, MaxLODSizeTexturePack: 512, LODBias: 2, LODBiasTexturePack: 2, MinMagFilter: "Aniso", MipFilter: "Point", MipGenSettings: "TMGS_SimpleAverage"},
	TEXTUREGROUP_Weapon: {MinLODSize: 64, MaxLODSize: 256, MaxLODSizeTexturePack: 256, LODBias: 2, LODBiasTexturePack: 2, MinMagFilter: "Aniso", MipFilter: "Point", MipGenSettings: "TMGS_SimpleAverage"},
	TEXTUREGROUP_WeaponNormalMap: {MinLODSize: 64, MaxLODSize: 256, MaxLODSizeTexturePack: 256, LODBias: 2, LODBiasTexturePack: 2, MinMagFilter: "Aniso", MipFilter: "Point", MipGenSettings: "TMGS_SimpleAverage"},
	TEXTUREGROUP_WeaponSpecular: {MinLODSize: 64, MaxLODSize: 256, MaxLODSizeTexturePack: 256, LODBias: 2, LODBiasTexturePack: 2, MinMagFilter: "Aniso", MipFilter: "Point", MipGenSettings: "TMGS_SimpleAverage"},
	TEXTUREGROUP_Vehicle: {MinLODSize: 64, MaxLODSize: 512, MaxLODSizeTexturePack: 512, LODBias: 2, LODBiasTexturePack: 2, MinMagFilter: "Aniso", MipFilter: "Point", MipGenSettings: "TMGS_SimpleAverage"},
	TEXTUREGROUP_VehicleNormalMap: {MinLODSize: 64, MaxLODSize: 512, MaxLODSizeTexturePack: 512, LODBias: 2, LODBiasTexturePack: 2, MinMagFilter: "Aniso", MipFilter: "Point", MipGenSettings: "TMGS_SimpleAverage"},
	TEXTUREGROUP_VehicleSpecular: {MinLODSize: 64, MaxLODSize: 512, MaxLODSizeTexturePack: 512, LODBias: 2, LODBiasTexturePack: 2, MinMagFilter: "Aniso", MipFilter: "Point", MipGenSettings: "TMGS_SimpleAverage"},
	TEXTUREGROUP_Cinematic: {MinLODSize: 128, MaxLODSize: 256, MaxLODSizeTexturePack: 256, LODBias: 2, LODBiasTexturePack: 2, MinMagFilter: "Aniso", MipFilter: "Point", MipGenSettings: "TMGS_SimpleAverage"},
	TEXTUREGROUP_Effects: {MinLODSize: 32, MaxLODSize: 256, MaxLODSizeTexturePack: 256, LODBias: 2, LODBiasTexturePack: 2, MinMagFilter: "Linear", MipFilter: "Point", MipGenSettings: "TMGS_SimpleAverage"},
	TEXTUREGROUP_EffectsNotFiltered: {MinLODSize: 32, MaxLODSize: 256, MaxLODSizeTexturePack: 256, LODBias: 2, LODBiasTexturePack: 2, MinMagFilter: "Aniso", MipFilter: "Point", MipGenSettings: "TMGS_SimpleAverage"},
	TEXTUREGROUP_Skybox: {MinLODSize: 64, MaxLODSize: 256, MaxLODSizeTexturePack: 256, LODBias: 2, LODBiasTexturePack: 2, MinMagFilter: "Aniso", MipFilter: "Point", MipGenSettings: "TMGS_SimpleAverage"},
	TEXTUREGROUP_UI: {MinLODSize: 1, MaxLODSize: 2048, MaxLODSizeTexturePack: 2048, LODBias: 0, LODBiasTexturePack: 0, MinMagFilter: "Aniso", MipFilter: "Point", MipGenSettings: "TMGS_SimpleAverage"},
	TEXTUREGROUP_Lightmap: {MinLODSize: 1, MaxLODSize: 512, MaxLODSizeTexturePack: 512, LODBias: 3, LODBiasTexturePack: 3, MinMagFilter: "Aniso", MipFilter: "Point", MipGenSettings: "TMGS_SimpleAverage"},
	TEXTUREGROUP_Shadowmap: {MinLODSize: 1, MaxLODSize: 512, MaxLODSizeTexturePack: 512, LODBias: 3, LODBiasTexturePack: 3, MinMagFilter: "Aniso", MipFilter: "Point", NumStreamedMips: 3, MipGenSettings: "TMGS_SimpleAverage"},
	TEXTUREGROUP_RenderTarget: {MinLODSize: 1, MaxLODSize: 2048, MaxLODSizeTexturePack: 2048, LODBias: 0, LODBiasTexturePack: 0, MinMagFilter: "Aniso", MipFilter: "Point", MipGenSettings: "TMGS_SimpleAverage"},
	TEXTUREGROUP_MobileFlattened: {MinLODSize: 1, MaxLODSize: 4096, MaxLODSizeTexturePack: 4096, LODBias: 1, LODBiasTexturePack: 1, MinMagFilter: "Linear", MipFilter: "Point", MipGenSettings: "TMGS_SimpleAverage"},
	TEXTUREGROUP_ProcBuilding_Face: {MinLODSize: 1, MaxLODSize: 1024, MaxLODSizeTexturePack: 1024, LODBias: 1, LODBiasTexturePack: 1, MinMagFilter: "Linear", MipFilter: "Point", MipGenSettings: "TMGS_SimpleAverage"},
	TEXTUREGROUP_ProcBuilding_LightMap: {MinLODSize: 1, MaxLODSize: 256, MaxLODSizeTexturePack: 256, LODBias: 1, LODBiasTexturePack: 1, MinMagFilter: "Linear", MipFilter: "Point", MipGenSettings: "TMGS_SimpleAverage"},
	TEXTUREGROUP_Terrain_Heightmap: {MinLODSize: 1, MaxLODSize: 4096, MaxLODSizeTexturePack: 4096, LODBias: 0, LODBiasTexturePack: 0, MinMagFilter: "Linear", MipFilter: "Point", MipGenSettings: "TMGS_SimpleAverage"},
	TEXTUREGROUP_Terrain_Weightmap: {MinLODSize: 1, MaxLODSize: 4096, MaxLODSizeTexturePack: 4096, LODBias: 0, LODBiasTexturePack: 0, MinMagFilter: "Linear", MipFilter: "Point", MipGenSettings: "TMGS_SimpleAverage"},
	TEXTUREGROUP_ImageBasedReflection: {MinLODSize: 256, MaxLODSize: 4096, MaxLODSizeTexturePack: 4096, LODBias: 1, LODBiasTexturePack: 1, MinMagFilter: "Linear", MipFilter: "Linear", MipGenSettings: "TMGS_Blur5"},
	TEXTUREGROUP_Bokeh: {MinLODSize: 1, MaxLODSize: 256, MaxLODSizeTexturePack: 256, LODBias: 1, LODBiasTexturePack: 1, MinMagFilter: "Linear", MipFilter: "Linear", MipGenSettings: "TMGS_SimpleAverage"},
	TEXTUREGROUP_UIStreamable: {MinLODSize: 1, MaxLODSize: 2048, MaxLODSizeTexturePack: 2048, LODBias: 0, LODBiasTexturePack: 0, MinMagFilter: "Aniso", MipFilter: "Point", NumStreamedMips: 0, MipGenSettings: "TMGS_SimpleAverage"},
	bAllowRagdolling: true,
	bAllowParticleSystemPerfBias: true,
	bAllowPerfThrottling: false,
	PerfScalingFramerateStart: 30.000000,
	PerfScalingFramerateRange: 20.000000,
	PerfScalingMaxReduction: 0.600000,
	PerfScalingBias: 0.200000,
	Borderless: false,
	StaticMeshLODBias: 1,
	bAllowDropShadows: false,
	SpeedTreeLODBias: 2,
	bUseLowQualMaterials: true,
	bUseSpectatorTextureSettings: false,
	TexturePoolSize: 150,
	AllowD3D11: false,
	PreferD3D11: false,
	FXAAQuality: 0,
	AllowScreenDoorFade: false,
	AllowScreenDoorLODFading: false,
	bAllowFog: false,
	MaterialQualityLevel: 1,
	SettingsVersion: 9,
	SpeedTreeWind: false,
	TEXTUREGROUP_NPC: {MinLODSize: 64, MaxLODSize: 512, MaxLODSizeTexturePack: 512, LODBias: 1, LODBiasTexturePack: 1, MinMagFilter: "Aniso", MipFilter: "Point", MipGenSettings: "TMGS_SimpleAverage"},
	TEXTUREGROUP_NPCNormalMap: {MinLODSize: 64, MaxLODSize: 256, MaxLODSizeTexturePack: 256, LODBias: 1, LODBiasTexturePack: 1, MinMagFilter: "Aniso", MipFilter: "Point", MipGenSettings: "TMGS_SimpleAverage"},
	TEXTUREGROUP_NPCSpecular: {MinLODSize: 64, MaxLODSize: 256, MaxLODSizeTexturePack: 256, LODBias: 1, LODBiasTexturePack: 1, MinMagFilter: "Aniso", MipFilter: "Point", MipGenSettings: "TMGS_SimpleAverage"},
	TEXTUREGROUP_WorldDetail: {MinLODSize: 32, MaxLODSize: 256, MaxLODSizeTexturePack: 256, LODBias: 3, LODBiasTexturePack: 3, MinMagFilter: "Aniso", MipFilter: "Point", MipGenSettings: "TMGS_SimpleAverage"},
	TEXTUREGROUP_TitleScreenPreview: {MinLODSize: 1, MaxLODSize: 2048, MaxLODSizeTexturePack: 2048, LODBias: 0, LODBiasTexturePack: 0, MinMagFilter: "Aniso", MipFilter: "Point", MipGenSettings: "TMGS_SimpleAverage"},
	TEXTUREGROUP_ColorLookupTable: {MinLODSize: 1, MaxLODSize: 4096, MaxLODSizeTexturePack: 1, LODBias: 0, LODBiasTexturePack: 0, MinMagFilter: "Aniso", MipFilter: "Point", MipGenSettings: "TMGS_SimpleAverage"}
}